services:
  - type: web
    name: jeevajyothi-backend
    runtime: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://jeevajyothi_user:jeevajyothi123@jeevajyothi.d1ezcde.mongodb.net/Jeevajyothimedia
      - key: JWT_SECRET
        value: jeevajyothi_media_secret_key_2024
      - key: ADMIN_EMAIL
        value: stephensam2001@gmail.com
      - key: ADMIN_PASSWORD
        value: admin@123
      - key: PORT
        value: 3000
